remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Jonathan R. Cangelosi
# description: <img align="center" width="200" height="200" src="photo.jpg">
